name: Deploy Site

on:
  workflow_dispatch:
    branches: [main]
  workflow_run:
    workflows: ['Release']
    branches: [main]
    types: 
      - completed

jobs:
  deploy-site:
    uses: batatinha-delivery/workflows/.github/workflows/site_deploy.yml@master
