name: Release

on: 
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Config Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install
        run: yarn --frozen-lockfile

      - name: Release it
        run: | 
          if [[ -f ".release-it.json" ]]; then
            yarn release-it --ci ${{ github.event.inputs.bump_type }}
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
