name: Deploy package

on:
  workflow_dispatch:
    branches: [main]

jobs:
  deploy-site:
    uses: batatinha-delivery/workflows/.github/workflows/npm_publish.yml@master
    secrets:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      NPM_DEPLOY_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
      GH_PAGES_DEPLOY: ${{ secrets.GH_PAGES_DEPLOY }}