name: Validate

on:
  workflow_call:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  validate_project:
    uses: batatinha-delivery/workflows/.github/workflows/npm_validate.yml@master
  validate_site:
    uses: batatinha-delivery/workflows/.github/workflows/site_validate.yml@master
